spring.application.name=UDECOM
server.port=yourserverport
spring.datasource.url=jdbc:postgresql://localhost:5432/ECOM
# Database username
spring.datasource.username=yordbusername
# Database password
spring.datasource.password=yourdbpassword
# PostgreSQL JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false

